language: csharp
dotnet: 2.1
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_script:
  - (cd ./src && dotnet restore)
  - chmod +x ./src/scripts/ci-run
script:
  - ./src/scripts/ci-run ./src Release
